from setuptools import setup, find_packages

setup(
    name="digame-app",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "fastapi==0.95.2",
        "uvicorn[standard]==0.23.0",
        "pydantic==1.10.8",
        "SQLAlchemy==2.0.18",
        "asyncpg==0.27.0",
        "python-dotenv==1.0.0",
        "torch==2.7.0",
        "scikit-learn==1.3.0",
        "pandas==2.0.3",
        "numpy==1.25.0",
        "joblib==1.3.2",
        "alembic==1.11.1",
        "python-jose[cryptography]==3.3.0",
        "python-multipart==0.0.6",
        "passlib[bcrypt]==1.7.4",
        "email-validator==2.0.0",
        "matplotlib==3.7.1",
        "seaborn==0.12.2",
        "plotly==5.14.1",
        "scipy==1.10.1",
        "networkx==3.1.0",
        "pyarrow==12.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "mypy>=1.0.0",
            "flake8>=6.0.0",
        ],
    },
    python_requires=">=3.8",
    description="Digame Platform App",
    author="Digame Team",
    author_email="info@example.com",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)