version: '3.8'

services:
  backend:
    container_name: digame_backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./digame:/app/digame
    environment:
      - DATABASE_URL=postgresql://digame_user:digame_password@db:5432/digame_db
      # Add other backend-specific environment variables here if needed
      # For example, if predictive.py needs specific model paths configurable via env vars:
      # - MODEL_PATH_PRIMARY=models/predictive_model.pth 
      # - MODEL_PATH_CUSTOM_EXAMPLE=digame/app/models/example_custom_model.pth
    depends_on:
      - db
    networks:
      - digame_network

  db:
    container_name: digame_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=digame_user
      - POSTGRES_PASSWORD=digame_password
      - POSTGRES_DB=digame_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Map to host 5433 to avoid conflict
    networks:
      - digame_network

volumes:
  postgres_data:

networks:
  digame_network:
