import pytest
import datetime
from typing import List, Dict, Any
import uuid

from digame.app.services.dashboard_service import DashboardService
from digame.app.models.dashboard_models import (
    CustomDashboard, DashboardLayout, WidgetConfig,
    AdvancedPerformanceSeries, AdvancedPerformanceDataPoint,
    PerformanceForecastData, BenchmarkComparisonData, ROIDashboardData
)

@pytest.fixture
def dashboard_service():
    # Reset the mock "DB" for each test
    DashboardService._custom_dashboards = {}
    return DashboardService()

@pytest.fixture
def sample_user_id():
    return 1

@pytest.fixture
def sample_tenant_id():
    return 1

@pytest.fixture
def sample_widget_config_data():
    return {
        "widget_type": "performance_forecast",
        "title": "Sales Forecast",
        "size": "medium",
        "position": {"x": 0, "y": 0},
        "settings": {"model_id": 123}
    }

# --- Test Custom Dashboard Management ---

async def test_create_custom_dashboard(dashboard_service: DashboardService, sample_tenant_id: int, sample_user_id: int):
    name = "My Test Dashboard"
    description = "A dashboard for testing"
    dashboard = await dashboard_service.create_custom_dashboard(
        tenant_id=sample_tenant_id,
        user_id=sample_user_id,
        name=name,
        description=description
    )
    assert dashboard.name == name
    assert dashboard.description == description
    assert dashboard.user_id == sample_user_id
    assert dashboard.tenant_id == sample_tenant_id
    assert dashboard.id in dashboard_service._custom_dashboards
    assert dashboard.layout.columns == 12
    assert len(dashboard.layout.widgets) == 0

async def test_get_custom_dashboard(dashboard_service: DashboardService, sample_tenant_id: int, sample_user_id: int):
    created_dashboard = await dashboard_service.create_custom_dashboard(sample_tenant_id, sample_user_id, "Test Dash")

    fetched_dashboard = await dashboard_service.get_custom_dashboard(created_dashboard.id, sample_user_id)
    assert fetched_dashboard is not None
    assert fetched_dashboard.id == created_dashboard.id

    # Test access by wrong user
    wrong_user_dashboard = await dashboard_service.get_custom_dashboard(created_dashboard.id, sample_user_id + 1)
    assert wrong_user_dashboard is None

    # Test non-existent dashboard
    non_existent_dashboard = await dashboard_service.get_custom_dashboard(str(uuid.uuid4()), sample_user_id)
    assert non_existent_dashboard is None

async def test_get_user_custom_dashboards(dashboard_service: DashboardService, sample_tenant_id: int, sample_user_id: int):
    await dashboard_service.create_custom_dashboard(sample_tenant_id, sample_user_id, "Dash 1")
    await dashboard_service.create_custom_dashboard(sample_tenant_id, sample_user_id, "Dash 2")
    # Dashboard for another user/tenant
    await dashboard_service.create_custom_dashboard(sample_tenant_id + 1, sample_user_id + 1, "Other Dash")

    user_dashboards = await dashboard_service.get_user_custom_dashboards(sample_user_id, sample_tenant_id)
    assert len(user_dashboards) == 2
    assert user_dashboards[0].name in ["Dash 1", "Dash 2"]

async def test_update_custom_dashboard_layout(dashboard_service: DashboardService, sample_tenant_id: int, sample_user_id: int, sample_widget_config_data: dict):
    dashboard = await dashboard_service.create_custom_dashboard(sample_tenant_id, sample_user_id, "Layout Test")

    new_widget = WidgetConfig(id=str(uuid.uuid4()), **sample_widget_config_data)
    new_layout = DashboardLayout(columns=8, widgets=[new_widget])

    updated_dashboard = await dashboard_service.update_custom_dashboard_layout(dashboard.id, sample_user_id, new_layout)
    assert updated_dashboard is not None
    assert updated_dashboard.layout.columns == 8
    assert len(updated_dashboard.layout.widgets) == 1
    assert updated_dashboard.layout.widgets[0].title == "Sales Forecast"

async def test_add_widget_to_dashboard(dashboard_service: DashboardService, sample_tenant_id: int, sample_user_id: int, sample_widget_config_data: dict):
    dashboard = await dashboard_service.create_custom_dashboard(sample_tenant_id, sample_user_id, "Widget Test")

    widget_to_add = WidgetConfig(**sample_widget_config_data) # ID will be generated by service

    updated_dashboard = await dashboard_service.add_widget_to_dashboard(dashboard.id, sample_user_id, widget_to_add)
    assert updated_dashboard is not None
    assert len(updated_dashboard.layout.widgets) == 1
    assert updated_dashboard.layout.widgets[0].title == "Sales Forecast"
    assert updated_dashboard.layout.widgets[0].id is not None # Check ID was assigned

    # Add another widget
    widget_to_add_2 = WidgetConfig(id=str(uuid.uuid4()), widget_type="roi_summary", title="ROI Summary", size="small", position={"x":1, "y":0})
    updated_dashboard = await dashboard_service.add_widget_to_dashboard(dashboard.id, sample_user_id, widget_to_add_2)
    assert len(updated_dashboard.layout.widgets) == 2


async def test_remove_widget_from_dashboard(dashboard_service: DashboardService, sample_tenant_id: int, sample_user_id: int, sample_widget_config_data: dict):
    dashboard = await dashboard_service.create_custom_dashboard(sample_tenant_id, sample_user_id, "Remove Widget Test")

    widget1_data = sample_widget_config_data.copy()
    widget1_data["title"] = "Widget 1"
    widget1 = WidgetConfig(id=str(uuid.uuid4()), **widget1_data)

    widget2_data = sample_widget_config_data.copy()
    widget2_data["title"] = "Widget 2"
    widget2_data["widget_type"] = "benchmark_comparison"
    widget2 = WidgetConfig(id=str(uuid.uuid4()), **widget2_data)

    await dashboard_service.add_widget_to_dashboard(dashboard.id, sample_user_id, widget1)
    await dashboard_service.add_widget_to_dashboard(dashboard.id, sample_user_id, widget2)

    dashboard_with_widgets = await dashboard_service.get_custom_dashboard(dashboard.id, sample_user_id)
    assert len(dashboard_with_widgets.layout.widgets) == 2

    # Remove widget1
    updated_dashboard = await dashboard_service.remove_widget_from_dashboard(dashboard.id, sample_user_id, widget1.id)
    assert updated_dashboard is not None
    assert len(updated_dashboard.layout.widgets) == 1
    assert updated_dashboard.layout.widgets[0].id == widget2.id

    # Try removing non-existent widget
    no_change_dashboard = await dashboard_service.remove_widget_from_dashboard(dashboard.id, sample_user_id, str(uuid.uuid4()))
    assert len(no_change_dashboard.layout.widgets) == 1


# --- Test Advanced Analytics Data Fetching (Mock data validation) ---

async def test_get_multi_dimensional_performance_data(dashboard_service: DashboardService, sample_user_id: int):
    metric_ids = [1, 2]
    time_period = "7d"
    data = await dashboard_service.get_multi_dimensional_performance_data(sample_user_id, metric_ids, time_period)
    assert isinstance(data, list)
    assert len(data) == len(metric_ids)
    for series in data:
        assert isinstance(series, AdvancedPerformanceSeries)
        assert len(series.data_points) == 7 # Mock data generates 7 points
        assert isinstance(series.data_points[0], AdvancedPerformanceDataPoint)

async def test_get_performance_forecast_data(dashboard_service: DashboardService, sample_user_id: int):
    model_id = 1
    data = await dashboard_service.get_performance_forecast_data(sample_user_id, model_id)
    assert isinstance(data, PerformanceForecastData)
    assert data.title == "Performance Forecast (Next 7 Days)"
    assert len(data.series) == 2 # Actual and Forecast
    assert isinstance(data.series[0], AdvancedPerformanceSeries)

async def test_get_benchmark_comparison_data(dashboard_service: DashboardService, sample_user_id: int):
    entity_id = 101
    metric_name = "Efficiency"
    data = await dashboard_service.get_benchmark_comparison_data(sample_user_id, entity_id, metric_name)
    assert isinstance(data, list)
    assert len(data) == 2 # Mock data returns two comparisons
    assert isinstance(data[0], BenchmarkComparisonData)
    assert data[0].metric_name == metric_name

async def test_get_roi_dashboard_data(dashboard_service: DashboardService, sample_user_id: int):
    project_ids = [1, 2]
    data = await dashboard_service.get_roi_dashboard_data(sample_user_id, project_ids)
    assert isinstance(data, ROIDashboardData)
    assert data.title == "Project ROI Overview"
    assert len(data.top_performing_projects) == 2
    assert len(data.roi_trend) == 3
    assert isinstance(data.roi_trend[0], AdvancedPerformanceDataPoint)
