"""add composite indexes

Revision ID: 662a682a6173
Revises: 20250523_multi_tenancy
Create Date: 2024-05-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662a682a6173'
down_revision = '20250523_multi_tenancy' # Assuming this is the correct down_revision from the file name
branch_labels = None
depends_on = None


def upgrade():
    from alembic import context
    from sqlalchemy.exc import ProgrammingError
    
    connection = context.get_bind()
    
    def index_exists(index_name, table_name):
        """Check if an index exists using raw SQL"""
        try:
            result = connection.execute(sa.text(f"""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes
                    WHERE schemaname = 'public'
                    AND tablename = '{table_name}'
                    AND indexname = '{index_name}'
                );
            """))
            return result.scalar()
        except Exception:
            # Fallback: try to create and catch error
            return False
    
    def create_index_safe(index_name, table_name, columns, unique=False):
        """Safely create an index, handling conflicts"""
        if not index_exists(index_name, table_name):
            try:
                op.create_index(index_name, table_name, columns, unique=unique)
                print(f"✓ Created index: {index_name}")
            except ProgrammingError as e:
                if "already exists" in str(e).lower():
                    print(f"✓ Index {index_name} already exists")
                else:
                    raise
        else:
            print(f"✓ Index {index_name} already exists")
    
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: digital_activities table doesn't exist yet, so skipping its index
    # The index is already defined in the Activity model __table_args__
    create_index_safe('ix_behavioral_patterns_model_id_pattern_label', 'behavioral_patterns', ['model_id', 'pattern_label'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_behavioral_patterns_model_id_pattern_label', table_name='behavioral_patterns')
    # Note: digital_activities index was not created in upgrade, so not dropping it here
    # ### end Alembic commands ###
