"""Add advanced analytics features

Revision ID: 20250701_1000
Revises: <REPLACE_WITH_PREVIOUS_REVISION_ID>
Create Date: 2025-07-01 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250701_1000'
down_revision = None # Replace this with the actual ID of the migration this one succeeds
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create ComparativeBenchmark table
    op.create_table('comparative_benchmarks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('benchmark_uuid', sa.String(length=36), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('source', sa.String(length=255), nullable=True),
        sa.Column('metric_name', sa.String(length=255), nullable=False),
        sa.Column('entity_type', sa.String(length=100), nullable=True),
        sa.Column('industry_segment', sa.String(length=100), nullable=True),
        sa.Column('region', sa.String(length=100), nullable=True),
        sa.Column('company_size', sa.String(length=50), nullable=True),
        sa.Column('benchmark_value', sa.Float(), nullable=False),
        sa.Column('value_type', sa.String(length=50), server_default='average', nullable=False),
        sa.Column('unit', sa.String(length=50), nullable=True),
        sa.Column('period_start_date', sa.DateTime(), nullable=True),
        sa.Column('period_end_date', sa.DateTime(), nullable=True),
        sa.Column('data_freshness_date', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('confidence_level', sa.Float(), nullable=True),
        sa.Column('lower_bound', sa.Float(), nullable=True),
        sa.Column('upper_bound', sa.Float(), nullable=True),
        sa.Column('sample_size', sa.Integer(), nullable=True),
        sa.Column('dimensions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparative_benchmarks_benchmark_uuid'), 'comparative_benchmarks', ['benchmark_uuid'], unique=True)
    op.create_index(op.f('ix_comparative_benchmarks_category'), 'comparative_benchmarks', ['category'], unique=False)
    op.create_index(op.f('ix_comparative_benchmarks_industry_segment'), 'comparative_benchmarks', ['industry_segment'], unique=False)
    op.create_index(op.f('ix_comparative_benchmarks_metric_name'), 'comparative_benchmarks', ['metric_name'], unique=False)
    op.create_index(op.f('ix_comparative_benchmarks_name'), 'comparative_benchmarks', ['name'], unique=False)
    op.create_index(op.f('ix_comparative_benchmarks_region'), 'comparative_benchmarks', ['region'], unique=False)
    op.create_index(op.f('ix_comparative_benchmarks_tenant_id'), 'comparative_benchmarks', ['tenant_id'], unique=False)

    # Add columns to analytics_models table
    op.add_column('analytics_models', sa.Column('dimensions', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('analytics_models', sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('analytics_models', sa.Column('aggregation_types', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False))

    # Modify analytics_predictions table
    op.alter_column('analytics_predictions', 'predicted_value', existing_type=sa.FLOAT(), nullable=True)
    op.add_column('analytics_predictions', sa.Column('predicted_values_multi_dim', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('analytics_predictions', sa.Column('benchmark_comparison_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('analytics_predictions', sa.Column('raw_prediction_output', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # Add column to reports table
    op.add_column('reports', sa.Column('export_config', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove column from reports table
    op.drop_column('reports', 'export_config')

    # Revert modifications to analytics_predictions table
    op.drop_column('analytics_predictions', 'raw_prediction_output')
    op.drop_column('analytics_predictions', 'benchmark_comparison_data')
    op.drop_column('analytics_predictions', 'predicted_values_multi_dim')
    op.alter_column('analytics_predictions', 'predicted_value', existing_type=sa.FLOAT(), nullable=False)

    # Remove columns from analytics_models table
    op.drop_column('analytics_models', 'aggregation_types')
    op.drop_column('analytics_models', 'metrics')
    op.drop_column('analytics_models', 'dimensions')

    # Drop ComparativeBenchmark table
    op.drop_index(op.f('ix_comparative_benchmarks_tenant_id'), table_name='comparative_benchmarks')
    op.drop_index(op.f('ix_comparative_benchmarks_region'), table_name='comparative_benchmarks')
    op.drop_index(op.f('ix_comparative_benchmarks_name'), table_name='comparative_benchmarks')
    op.drop_index(op.f('ix_comparative_benchmarks_metric_name'), table_name='comparative_benchmarks')
    op.drop_index(op.f('ix_comparative_benchmarks_industry_segment'), table_name='comparative_benchmarks')
    op.drop_index(op.f('ix_comparative_benchmarks_category'), table_name='comparative_benchmarks')
    op.drop_index(op.f('ix_comparative_benchmarks_benchmark_uuid'), table_name='comparative_benchmarks')
    op.drop_table('comparative_benchmarks')
    # ### end Alembic commands ###
