"""Add dashboard models and enhance analytics model

Revision ID: 20250704_0001
Revises: 20250703_0001_add_custom_dashboards_enhance_perf_metric
Create Date: 2025-07-04 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # If using JSONB specific to PostgreSQL

# revision identifiers, used by Alembic.
revision = '20250704_0001'
down_revision = '20250703_0001_add_custom_dashboards_enhance_perf_metric' # Replace with actual previous revision
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add columns to analytics_models table
    op.add_column('analytics_models', sa.Column('model_path', sa.String(length=512), nullable=True))
    op.add_column('analytics_models', sa.Column('training_metadata', sa.JSON(), nullable=True))

    # Create analytics_dashboards table
    op.create_table('analytics_dashboards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dashboard_uuid', sa.String(length=36), nullable=True),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('layout', sa.JSON(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_dashboards_dashboard_uuid'), 'analytics_dashboards', ['dashboard_uuid'], unique=True)
    op.create_index(op.f('ix_analytics_dashboards_tenant_id'), 'analytics_dashboards', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analytics_dashboards_user_id'), 'analytics_dashboards', ['user_id'], unique=False)

    # Create dashboard_widget_configs table
    op.create_table('dashboard_widget_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('widget_uuid', sa.String(length=36), nullable=True),
        sa.Column('dashboard_id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('widget_type', sa.String(length=100), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('data_source_config', sa.JSON(), nullable=False),
        sa.Column('display_options', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['dashboard_id'], ['analytics_dashboards.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widget_configs_dashboard_id'), 'dashboard_widget_configs', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widget_configs_tenant_id'), 'dashboard_widget_configs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widget_configs_widget_uuid'), 'dashboard_widget_configs', ['widget_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop dashboard_widget_configs table
    op.drop_index(op.f('ix_dashboard_widget_configs_widget_uuid'), table_name='dashboard_widget_configs')
    op.drop_index(op.f('ix_dashboard_widget_configs_tenant_id'), table_name='dashboard_widget_configs')
    op.drop_index(op.f('ix_dashboard_widget_configs_dashboard_id'), table_name='dashboard_widget_configs')
    op.drop_table('dashboard_widget_configs')

    # Drop analytics_dashboards table
    op.drop_index(op.f('ix_analytics_dashboards_user_id'), table_name='analytics_dashboards')
    op.drop_index(op.f('ix_analytics_dashboards_tenant_id'), table_name='analytics_dashboards')
    op.drop_index(op.f('ix_analytics_dashboards_dashboard_uuid'), table_name='analytics_dashboards')
    op.drop_table('analytics_dashboards')

    # Remove columns from analytics_models table
    op.drop_column('analytics_models', 'training_metadata')
    op.drop_column('analytics_models', 'model_path')

    # ### end Alembic commands ###
