"""add_custom_dashboards_enhance_perf_metric

Revision ID: 20250703_0001
Revises: 20250701_1000_add_advanced_analytics_features
Create Date: 2025-07-03 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # If using JSONB specifically for PostgreSQL

# revision identifiers, used by Alembic.
revision = '20250703_0001'
down_revision = '20250701_1000_add_advanced_analytics_features' # Assuming this is the previous one
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add columns to performance_metrics table
    op.add_column('performance_metrics', sa.Column('dimensions_values', sa.JSON(), nullable=True))
    op.add_column('performance_metrics', sa.Column('predicted_by_model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_performance_metrics_predicted_by_model_id_analytics_models',
        'performance_metrics', 'analytics_models',
        ['predicted_by_model_id'], ['id']
    )

    # Create dashboard_widgets table
    op.create_table('dashboard_widgets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('widget_uuid', sa.String(length=36), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('widget_type', sa.String(length=100), nullable=False),
        sa.Column('data_source_config', sa.JSON(), nullable=False),
        sa.Column('display_options', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_dashboard_widgets_tenant_id_tenants'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('widget_uuid')
    )
    op.create_index(op.f('ix_dashboard_widgets_id'), 'dashboard_widgets', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_tenant_id'), 'dashboard_widgets', ['tenant_id'], unique=False)

    # Create analytics_dashboards table
    op.create_table('analytics_dashboards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dashboard_uuid', sa.String(length=36), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('layout', sa.JSON(), nullable=False),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True, default=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_analytics_dashboards_tenant_id_tenants'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_analytics_dashboards_user_id_users'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('dashboard_uuid')
    )
    op.create_index(op.f('ix_analytics_dashboards_id'), 'analytics_dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_dashboards_tenant_id'), 'analytics_dashboards', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analytics_dashboards_user_id'), 'analytics_dashboards', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop analytics_dashboards table
    op.drop_index(op.f('ix_analytics_dashboards_user_id'), table_name='analytics_dashboards')
    op.drop_index(op.f('ix_analytics_dashboards_tenant_id'), table_name='analytics_dashboards')
    op.drop_index(op.f('ix_analytics_dashboards_id'), table_name='analytics_dashboards')
    op.drop_table('analytics_dashboards')

    # Drop dashboard_widgets table
    op.drop_index(op.f('ix_dashboard_widgets_tenant_id'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')

    # Remove columns from performance_metrics table
    op.drop_constraint('fk_performance_metrics_predicted_by_model_id_analytics_models', 'performance_metrics', type_='foreignkey')
    op.drop_column('performance_metrics', 'predicted_by_model_id')
    op.drop_column('performance_metrics', 'dimensions_values')

    # ### end Alembic commands ###
