"""add composite indexes

Revision ID: 662a682a6173
Revises: 20250523_multi_tenancy
Create Date: 2024-05-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662a682a6173'
down_revision = '20250523_multi_tenancy' # Assuming this is the correct down_revision from the file name
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_digital_activities_user_id_timestamp', 'digital_activities', ['user_id', 'timestamp'], unique=False)
    op.create_index('ix_behavioral_patterns_model_id_pattern_label', 'behavioral_patterns', ['model_id', 'pattern_label'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_behavioral_patterns_model_id_pattern_label', table_name='behavioral_patterns')
    op.drop_index('ix_digital_activities_user_id_timestamp', table_name='digital_activities')
    # ### end Alembic commands ###
